codigo_banco: 0..2
lote_servico: 3..6
tipo_registro: 7..7
tipo_operacao: 8..8
tipo_servico: 9..10
filler_a: 11..12
num_versao_lote: 13..15
filler_b: 16..16
tipo_inscr_empresa: 17..17
num_inscr_empresa: 18..32
cod_convenio_banco: 33..52
ag_mantenedora_conta: 53..57
dig_verif_agencia: 58..58
num_conta_corrente: 59..70
dig_verif_conta: 71..71
dig_verif_ag_conta: 72..72
nome_empresa: 73..102
filler_c: 103..239
