codigo_banco: 0..2
lote_servico: 3..6
tipo_registro: 7..7
num_seq_registro_lote: 8..12
cod_segmento_reg_detalhe: 13..13
filler_a: 14..14
cod_mov_remessa: 15..16
codigo_barras: 17..60
tipo_inscricao_cedente: 61..61
num_inscricao_cedente: 62..76
nome_cedente: 77..106
data_vencimento_titulo: 107..114
valor_nominal_titulo: 115..129
quantidade_moeda: 130..144
codigo_moeda: 145..146
num_doc_cobranca: 147..161
agencia_enc_cobranca: 162..166
dig_verif_agencia: 167..167
praca_cobradora: 168..177
codigo_carteira: 178..178
especie_titulo: 179..180
data_emissao_titulo: 181..188
juros_mora_dia: 189..203
cod_desconto_1: 204..204
data_desconto_1: 205..212
valor_percentual_desconto_1: 213..227
cod_protesto: 228..228
num_dias_protesto: 229..230
data_limite_pagamento_titulo: 231..238
tipo_titulo: 239..239
