banco: 0..2
lote: 3..6
registro: 7..7
tipo_operacao: 8..8
tipo_servico: 9..10
zeros: 11..12
layout_lote: 13..15
brancos1: 16..16
cod_inscricao: 17..17
num_inscricao: 18..32
convenio: 33..52
agencia: 53..57
dv_agencia: 58..58
conta_corrente: 59..70
conta_dv: 71..71
dv_conta_agencia: 72..72
nome_empresa: 73..102
brancos2: 103..239