banco: 0..2
lote: 3..6
registro: 7..7
compl_registro: 8..16
tipo_inscricao: 17..17
num_inscr_empresa: 18..31
cod_convenio: 32..51
ag_mantenedora_conta: 52..56
dv_agencia: 57..57
num_conta_corrente: 58..69
dv_conta_corrente: 70..70
dv_agencia_conta: 71..71
nome_empresa: 72..101
nome_banco: 102..131
compl_registro2: 132..141
cod_arquivo_retorno: 142..142
data_geracao_arquivo: 143..150
hora_geracao_arquivo: 151..156
num_seq_arquivo_retorno: 157..162
num_versao_layout_arquivo: 163..165
compl_registro3: 166..239