banco: 0..2
lote: 3..6
registro: 7..7
tipo_operacao: 8..8
tipo_servico: 9..10
compl_registro: 11..12
layout_lote: 13..15
compl_registro1: 16..16
tipo_inscricao: 17..17
num_inscr_empresa: 18..32
cod_convenio: 33..52
ag_mantenedora_conta: 53..57
dv_agencia: 58..58
num_conta_corrente: 59..70
dv_conta: 71..71
dv_conta_agencia: 72..72
nome_empresa: 73..102
compl_registro2: 103..239