banco: 0..2
lote: 3..6
registro: 7..7
brancos1: 8..16
cod_inscricao: 17..17
num_inscricao: 18..31
cod_convenio: 32..51
agencia: 52..56
dv_agencia: 57..57
num_conta_correbte: 58..69
conta_corrente_dv: 70..70
agencia_conta_dv: 71..71
nome_empresa: 72..101
nome_banco: 102..131
brancos2: 132..141
cod_arquivo_retorno: 142..142
data_geracao_arquivo: 143..150
hora_geracao_arquivo: 151..156
num_seq_arquivo_retorno: 157..162
num_versao_layout_arquivo: 163..165
brancos3: 166..239