banco: 0..2
lote: 3..6
tipo_registro: 7..7
num_registro: 8..12
segmento: 13..13
res_banco1: 14..14
cod_movimentacao: 15..16
cod_banco: 17..19
cod_moeda_cod_barras: 20..20
dv_cod_barras: 21..21
fator_vencimento: 22..25
valor: 26..35
campo_livre: 36..60
cod_inscricao_cedente: 61..61
num_inscricao_cedente: 62..76
nome_cedente: 77..106
data_vencimento_titulo: 107..114
valor_nominal_titulo: 115..129
quantidade_moeda: 130..144
cod_moeda: 145..146
num_documento: 147..161
agencia_cobradora: 162..166
dv_agencia_cobradora: 167..167
praca_cobradora: 168..177
carteira: 178..178
especie_titulo: 179..180
emissao: 181..188
juros: 189..203
cod_desconto_1: 204..204
data_desconto_1: 205..212
valor_percentual_desconto_1: 213..227
cod_protesto: 228..228
num_dias_protesto: 229..230
data_limite_pagamento: 231..238
tipo_titulo: 239..239
