banco: 0..2
lote: 3..6
tipo_registro: 7..7
num_registro: 8..12
segmento: 13..13
res_banco1: 14..14
cod_movimentacao: 15..16
acrescimos: 17..31
valor_desconto: 32..46
valor_abatimento: 47..61
valor_iof: 62..76
valor_pago: 77..91
valor_liquido: 92..106
outras_despesas: 107..121
outros_creditos: 122..136
data_ocorrencia: 137..144
data_credito: 145..152
cod_ocorrencia_sacado: 153..156
data_ocorrencia_sacado: 157..164
valor_ocorrencia_sacado: 165..179
compl_ocorrencia_sacado: 180..209
cod_banco: 210..212
res_banco2: 213..239