banco: 0..2
lote: 3..6
tipo_registro: 7..7
num_registro: 8..12
segmento: 13..13
res_banco1: 14..14
cod_movimentacao: 15..16
agencia: 17..20
dv_agencia: 21..21
conta_corrente: 22..30
dv_conta: 31..31
res_banco1: 32..39
id_titulo: 40..52
carteira: 53..53
doc_cobranca: 54..68
vencimento: 69..76
valor_titulo: 77..91
banco_recebimento: 92..94
ag_recebimento: 95..98
dv_ag_recebimento: 99..99
id_titulo_empresa: 100..124
cod_moeda: 125..126
tipo_inscricao: 127..127
num_inscricao: 128..142
nome: 143..182
conta_cobranca: 183..192
valor_tarifa: 193..207
identificacao: 208..217
res_banco2: 218..239